# -*- coding: utf-8 -*-
"""Barkavi.G VAC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T2qTzSN0kZSZfYccA-_6raz-LiKFojWz
"""

def bubbleSort(arr):
	n = len(arr)
	swapped = False
	for i in range(n-1):
		for j in range(0, n-i-1):

			if arr[j] > arr[j + 1]:
				swapped = True
				arr[j], arr[j + 1] = arr[j + 1], arr[j]
		
		if not swapped:
			return



arr = [34, 5, 25, 57, 81, 76, 60, 44, 89, 345, 91, 23,78, 64, 59, 118]

bubbleSort(arr)

print("Sorted array is:")
for i in range(len(arr)):
	print("% d" % arr[i], end=" ")